* Mas afinal, o que o back end vai fazer?
+ Receber currículo do front end
+ Cadastrar um novo currículo
+ Deletar um currículo cadastrado
+ Mandar currículo pro front end
+ Verificar se um currículo já existe no banco de dados
+ Verificar se um usuário digitou CPF e senha corretos
** Cadastrar um novo usuário
Um usuario registra todos os seus dados no sistema e então o front end envia esses dados na forma de JSON pro back end. O front end deve verificar se o CPF já foi cadastrado antes de enviar os dados pro backend, ele faz isso pela funcao verUsuario.

Isso é feito no endpoint nov.
** Mandar dados pro front end
O frontend pode consultar por um curriculo já cadastrado. O frontend faz uma busca usando o id do curriculo. Se o curriculo existe, o backend retorna como JSON o curriculo do banco de dados. Se não existe, o backend retorna NULL.

Isso é feito no endpoint cur.
** Editar um usuário
Primeiramente, no front end o usuário digita CPF e senha. O back end então tem que dizer se esse usuário tem ou não autorização de editar os dados. Se o back dizer pro front que sim, o frontend pede os dados do currículo associado ao CPF e vai pra tela de edição, onde da pra editar tudo menos CPF e senha. O front então manda esses dados de volta pro backend pra ser salvos.

Isso é feito no endpoint edit.
** deletar um usuário
Igual no editar o usuário, primeiramente o usuário entra CPF e senha. O frontend verifica se o currículo associado existe no banco de dados e verifica se a senha ta certa. Se existir e a senha estiver correta, o banco de dados retorna autorização pro front end. Quando o front end recebe a autorização, ele faz um pedido pro banco de dados deletar o arquivo.

Isso é feito no endpoint del.
** Verificar se um usuário já existe no banco de dados
Um pedido é enviado ao backend pedindo confirmação sobre se já existe um usuário no banco de dados associado a um CPF.

Isso é feito no endpoint verU.
** Autenticar um usuário
Autentica um usuário pelo cpf e pela seha pra conceder permissão de editar dados do currículo ou de deletar seu currículo do banco de dados.

Isso é feito no endpoint auth.
** Endpoints da API:
*** nov (POST)
recebe dados de um curriculo pra gravar ele no disco.
*** cur (GET)
retorna os dados de um currículo para o frontend
*** edit (POST)
edita um currículo já existente com dados novos
*** del (POST)
diz pro backend deletar um curriculo se o cpf e senha fornecidos forem válidos.
*** auth (POST)
verifica se um usuário existe e forneceu a senha correta.
*** verU (GET)
verifica se um usuário já existe no banco de dados
